### ISSUE TITLE
Can support Gcode from fusion360 ?

### ISSUE THREAD

**Issue by Witawat** [alvarogimenez/g-code-utils#10]
Can support Gcode from fusion360 ?
i try not work
![image](https://user-images.githubusercontent.com/4926369/199868366-46c87101-d713-4df9-aca8-a781647ce7d8.png)
![image](https://user-images.githubusercontent.com/4926369/199868387-4ff85456-6825-401f-a908-4f7fd8305e62.png)

org file
![image](https://user-images.githubusercontent.com/4926369/199868434-79639319-6a95-4334-baa6-46374ced80bd.png)

[LED6PCS.zip](https://github.com/alvarogimenez/g-code-utils/files/9934336/LED6PCS.zip)

**Comment by alvarogimenez** [comment]
That's something I would like to do in the future, indeed. Currently the software only supports linear G00 and G01 instructions. Fusion360's G-Code include arcs (G2) and other non-linear instructions which are harder to translate. However, I don't have the time right now to work on this, but I will keep this issue open for a while in case I can spend a few hours.

**Comment by alvarogimenez** [comment]
Hey there! This took longer than I expected since I've been very busy in the past few months but I've finally managed to tackle G2/G3 support. I've just released a new version ([1.2.1](https://github.com/alvarogimenez/g-code-utils/releases/tag/v1.2.1)) with a lot of improvements including supporting Fusion 360 code 😄 I hope it works for you and thanks for your support and patience!
